In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("global_superstore_2016.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  str
 10  State           51290 non-null  str
 11  Country         51290 non-null  str
 12  Region          51290 non-null  str
 13  Market          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  str
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  str
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(3), int64(2), str(19)
memory usage: 9.4 MB

In [4]:
df.head(n = 2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical

In [5]:
df.describe()

            Row ID   Postal Code      Quantity      Discount  Shipping Cost
count  51290.00000   9994.000000  51290.000000  51290.000000   51290.000000
mean   25645.50000  55190.379428      3.476545      0.142908      26.478567
std    14806.29199  32063.693350      2.278766      0.212280      57.251373
min        1.00000   1040.000000      1.000000      0.000000       1.002000
25%    12823.25000  23223.000000      2.000000      0.000000       2.610000
50%    25645.50000  56430.500000      3.000000      0.000000       7.790000
75%    38467.75000  90008.000000      5.000000      0.200000      24.450000
max    51290.00000  99301.000000     14.000000      0.850000     933.570000

In [6]:
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")
df["Order Date"] = pd.to_datetime(df["Order Date"],format = "mixed")

In [7]:
df.head(n=3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium

### **1. Total, how many orders have cross the shipping cost of 500?**

In [8]:
if df["Shipping Cost"].astype(str).str.contains("$", regex=False).any():
    df["Shipping Cost"].astype(str).str.replce("$",regex = False)

In [9]:
df[df["Shipping Cost"]>500.00][:3]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium

In [10]:
len(df[df["Shipping Cost"]>500.00])

120

### **2. Count the number of segments, countries, regions, markets, categories, and sub-categories present in the global_superstore_2016 data.**

In [11]:
df[["Segment","Country","Region","Market","Category","Sub-Category"]].nunique()

Segment           3
Country         165
Region           23
Market            5
Category          3
Sub-Category     17
dtype: int64

In [12]:
df["Segment"].value_counts()

Segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [13]:
df["Country"].value_counts()

Country
United States    9994
Australia        2837
France           2827
Mexico           2635
Germany          2063
                 ...
Kuwait              1
Malawi              1
Bhutan              1
Suriname            1
The Gambia          1
Name: count, Length: 165, dtype: int64

In [14]:
df["Region"].value_counts()

Region
Western Europe       5883
Central America      5616
Oceania              3487
Western US           3203
Southeastern Asia    3129
South America        2988
Eastern US           2848
Southern Asia        2655
Western Asia         2440
Eastern Asia         2374
Central US           2323
Northern Europe      2204
Southern Europe      2113
Caribbean            1690
Southern US          1620
Eastern Europe       1529
Western Africa       1460
North Africa         1278
Eastern Africa        728
Central Africa        643
Southern Africa       478
Canada                384
Central Asia          217
Name: count, dtype: int64

In [15]:
df["Market"].value_counts()

Market
Asia Pacific    14302
Europe          11729
USCA            10378
LATAM           10294
Africa           4587
Name: count, dtype: int64

In [16]:
df["Category"].value_counts()

Category
Office Supplies    31289
Technology         10141
Furniture           9860
Name: count, dtype: int64

In [17]:
df["Sub-Category"].value_counts()

Sub-Category
Binders        6146
Storage        5049
Art            4864
Paper          3492
Chairs         3434
Phones         3357
Furnishings    3154
Accessories    3075
Fasteners      2601
Labels         2601
Bookcases      2411
Supplies       2407
Envelopes      2387
Copiers        2223
Appliances     1742
Machines       1486
Tables          861
Name: count, dtype: int64

### **3. Get the list of Order ID's where the Indian customer's have bought the things under the category 'Technology' after paying the Shipping Cost more than 500.**

In [18]:
details = (df["Country"] == "India") & (df["Category"] == "Technology") &(df["Shipping Cost"]>500.00)

In [19]:
indian_order = df[details].copy()

In [20]:
indian_order

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
41,29272,IN-2015-BF1100558-42319,2015-11-11,2015-11-15,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,TEC-PH-5269,Technology,Phones,"Motorola Smart Phone, with Caller ID","$4,518.78",7,0.0,$632.52,658.69,High
48,28701,IN-2015-SW2027558-42125,2015-05-01,2015-05-01,Same Day,SW-2027558,Scott Williamson,Consumer,NaN,Jamshedpur,...,TEC-MA-5007,Technology,Machines,"Konica Inkjet, White","$2,174.13",7,0.0,$500.01,637.86,Critical
55,29047,IN-2013-SG2047058-41424,2013-05-30,2013-05-31,First Class,SG-2047058,Sheri Gordon,Consumer,NaN,Bhopal,...,TEC-CO-4590,Technology,Copiers,"Hewlett Wireless Fax, Color","$1,526.52",4,0.0,$732.72,625.77,Critical
90,29600,IN-2013-GP1474058-41419,2013-05-25,2013-05-28,Second Class,GP-1474058,Guy Phonely,Corporate,NaN,Delhi,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$1,916.73",3,0.0,$498.33,548.40,Critical

### **4. Get the list of Order ID's where the Indian customer's have bought the things under the category 'Technology' the Sales greater than 500.**

In [21]:
if df["Sales"].astype(str).str.contains("$",regex = False).any():
    df["Sales"] = df["Sales"].astype(str).str.replace("$","",regex = False).copy()
if df["Sales"].astype(str).str.contains(",",regex = False).any():
    df["Sales"] = df["Sales"].astype(str).str.replace(",","",regex = False).copy()

In [22]:
df["Sales"] = df["Sales"].astype("float64")

In [23]:
indian_details = (df["Country"] == "India") & (df["Category"] == "Technology") & (df["Sales"] > 500.00)

In [24]:
indian_order_details = df[indian_details].copy()

In [25]:
indian_order_details["Order ID"]

41       IN-2015-BF1100558-42319
48       IN-2015-SW2027558-42125
55       IN-2013-SG2047058-41424
90       IN-2013-GP1474058-41419
130      IN-2014-SV2081558-41968
                  ...
14874    IN-2013-ML1826558-41503
15236    IN-2015-HG1484558-42339
23250    IN-2013-MA1799558-41565
24316    IN-2012-DP1316558-41173
35903    IN-2013-JS1568558-41371
Name: Order ID, Length: 163, dtype: str

In [26]:
len(indian_order_details)

163

### **5. How many people from the State 'Karnataka' have bought the things under the category 'Technology'?**

In [27]:
karnataka_order = (df["State"] == "Karnataka") & (df["Category"] == "Technology")

In [28]:
karnataka_order_details = df[karnataka_order]

In [29]:
len(karnataka_order_details)

21

In [30]:
karnataka_order_details

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
408,27724,IN-2015-CY1274558-42300,2015-10-23,2015-10-25,First Class,CY-1274558,Craig Yedwab,Corporate,NaN,Bangalore,...,TEC-CO-4578,Technology,Copiers,"Hewlett Fax Machine, Laser",959.76,3,0.0,$460.62,317.81,Critical
782,27579,IN-2015-JW1522058-42101,2015-04-07,2015-04-12,Standard Class,JW-1522058,Jane Waco,Corporate,NaN,Mangalore,...,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID",3271.20,5,0.0,"$1,341.15",232.45,High
1957,22906,IN-2014-RA1928558-41863,2014-08-12,2014-08-16,Standard Class,RA-1928558,Ralph Arnett,Consumer,NaN,Mangalore,...,TEC-CO-4791,Technology,Copiers,"HP Wireless Fax, High-Speed",1075.23,3,0.0,$344.07,136.45,High
2364,28779,IN-2014-BO1135058-41783,2014-05-24,2014-05-30,Standard Class,BO-1135058,Bill Overfelt,Corporate,NaN,Bangalore,...,TEC-CO-3608,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,$0.00,119.46,Medium
3200,22204,IN-2014-CM1238558-41755,2014-04-26,2014-04-28,Second Class,CM-1238558,Christopher Martinez,Consumer,NaN,Bangalore,...,TEC-CO-4769,Technology,Copiers,"HP Fax and Copier, Color",697.32,4,0.0,$292.80,94.93,High
5030,28814,IN-2015-MK1816058-42330,2015-11-22,2015-11-26,Standard Class,MK-1816058,Mike Kennedy,Consumer,NaN,Mangalore,...,TEC-CO-3609,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,$927.15,66.30,Medium
5132,28511,IN-2012-AH1046558-41059,2012-05-30,2012-05-30,Same Day,AH-1046558,Amy Hunt,Consumer,NaN,Belgaum,...,TEC-AC-5132,Technology,Accessories,"Logitech Numeric Keypad, Programmable",382.56,8,0.0,$68.64,65.04,Medium
5378,21739,IN-2014-TC2147558-41753,2014-04-24,2014-04-26,Second Class,TC-2147558,Tony Chapman,Home Office,NaN,Bangalore,...,TEC-PH-5266,Technology,Phones,"Motorola Signal Booster, with Caller ID",286.26,2,0.0,$19.98,62.00,Critical
5572,24372,IN-2015-Co1264058-42326,2015-11-18,2015-11-22,Standard Class,Co-1264058,Corey-Lock,Consumer,NaN,Bangalore,...,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID",654.24,1,0.0,$268.23,60.28,Medium
7304,22905,IN-2014-RA1928558-41863,2014-08-12,2014-08-16,Standard Class,RA-1928558,Ralph Arnett,Consumer,NaN,Mangalore,...,TEC-PH-3139,Technology,Phones,"Apple Office Telephone, Cordless",408.78,6,0.0,$192.06,46.71,High
12782,21980,IN-2013-MA1756058-41275,2013-01-01,2013-01-06,Standard Class,MA-1756058,Matt Abelman,Home Office,NaN,Bellary,...,TEC-AC-5194,Technology,Accessories,"Memorex Flash Drive, Erganomic",244.89,9,0.0,$65.88,24.56,High
12996,29865,IN-2013-MH1745558-41590,2013-11-12,2013-11-17,Second Class,MH-1745558,Mark Hamilton,Consumer,NaN,Bangalore,...,TEC-AC-5866,Technology,Accessories,"SanDisk Keyboard, Programmable",414.90,5,0.0,$124.35,24.00,Medium
14278,22904,IN-2014-RA1928558-41863,2014-08-12,2014-08-16,Standard Class,RA-1928558,Ralph Arnett,Consumer,NaN,Mangalore,...,TEC-MA-6139,Technology,Machines,"StarTech Card Printer, Wireless",163.50,1,0.0,$37.59,21.12,High
16364,23769,IN-2013-TB2152058-41430,2013-06-05,2013-06-10,Standard Class,TB-2152058,Tracy Blumstein,Consumer,NaN,Bangalore,...,TEC-PH-3127,Technology,Phones,"Apple Audio Dock, Cordless",339.48,2,0.0,$27.12,17.34,Medium
16877,27013,IN-2013-ON1871558-41636,2013-12-28,2014-01-02,Standard Class,ON-1871558,Odella Nelson,Corporate,NaN,Bangalore,...,TEC-MA-5542,Technology,Machines,"Panasonic Card Printer, Durable",347.88,2,0.0,$163.50,16.53,Medium
17155,24373,IN-2015-Co1264058-42326,2015-11-18,2015-11-22,Standard Class,Co-1264058,Corey-Lock,Consumer,NaN,Bangalore,...,TEC-AC-4152,Technology,Accessories,"Enermax Flash Drive, Erganomic",196.65,5,0.0,$82.50,16.11,Medium
18314,24367,IN-2015-Co1264058-42326,2015-11-18,2015-11-22,Standard Class,Co-1264058,Corey-Lock,Consumer,NaN,Bangalore,...,TEC-AC-5872,Technology,Accessories,"SanDisk Memory Card, Bluetooth",224.82,2,0.0,$6.72,14.51,Medium
18733,22205,IN-2014-CM1238558-41755,2014-04-26,2014-04-28,Second Class,CM-1238558,Christopher Martinez,Consumer,NaN,Bangalore,...,TEC-PH-3817,Technology,Phones,"Cisco Speaker Phone, VoIP",277.14,2,0.0,$38.76,13.96,High
21482,27041,IN-2014-PW1903058-41999,2014-12-26,2014-12-30,Standard Class,PW-1903058,Pauline Webber,Corporate,NaN,Shimoga,...,TEC-AC-5118,Technology,Accessories,"Logitech Keyboard, USB",145.32,2,0.0,$45.00,11.00,Medium
21675,23579,IN-2014-LC1688558-41940,2014-10-28,2014-10-30,Second Class,LC-1688558,Lena Creighton,Consumer,NaN,Bangalore,...,TEC-AC-3397,Technology,Accessories,"Belkin Numeric Keypad, Erganomic",177.75,3,0.0,$30.15,10.84,Medium
35956,20727,IN-2013-AT1043558-41607,2013-11-29,2013-12-03,Standard Class,AT-1043558,Alyssa Tate,Home Office,NaN,Bellary,...,TEC-AC-5101,Technology,Accessories,"Logitech Flash Drive, Programmable",32.01,1,0.0,$10.23,3.30,High

### **6. Get the list of countries where the 'Profit' and 'Shipping Cost's are greater than or equal to 2000 and 300 respectively.**

In [31]:
df["Profit"]  = df["Profit"].astype(str).str.strip()

In [32]:
if df["Profit"].astype(str).str.contains("$",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace("$","",regex = False).copy()
    
if df["Profit"].astype(str).str.contains(",",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace(",","",regex = False).copy()

if df["Profit"].astype(str).str.contains("(",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace("(","",regex = False).copy()

if df["Profit"].astype(str).str.contains(")",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace(")","",regex = False).copy()

In [33]:
df["Profit"] = pd.to_numeric(df["Profit"], errors="coerce")

In [34]:
if df["Shipping Cost"].astype(str).str.contains("$", regex=False).any():
    df["Shipping Cost"] = df["Shipping Cost"].astype(str).str.replce("$",regex = False)

In [35]:
df["Shipping Cost"] = pd.to_numeric(df["Shipping Cost"], errors = "coerce")

In [36]:
country_list = (df["Profit"] >= 2000) & (df["Shipping Cost"] >= 300)

In [37]:
country_list_details = df[country_list]

In [38]:
country_list_details[:3]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
17,12069,ES-2015-PJ1883564-42255,2015-09-08,2015-09-14,Standard Class,PJ-1883564,Patrick Jones,Corporate,NaN,Prato,...,OFF-AP-4743,Office Supplies,Appliances,"Hoover Stove, Red",7958.58,14,0.0,3979.08,778.32,Low
42,25795,IN-2015-VG2180558-42273,2015-09-26,2015-09-28,Second Class,VG-2180558,Vivek Grady,Corporate,NaN,Thiruvananthapuram,...,FUR-BO-5951,Furniture,Bookcases,"Sauder Classic Bookcase, Traditional",5667.87,13,0.0,2097.03,658.35,Medium
81,50788,MO-2015-DP310586-42305,2015-10-28,2015-10-30,Second Class,DP-310586,Dave Poirier,Corporate,NaN,Meknes,...,TEC-CO-3710,Technology,Copiers,"Canon Wireless Fax, Laser",5301.24,14,0.0,2597.28,568.45,Medium

In [39]:
len(country_list_details)

23

In [40]:
country_list_details["Country"].value_counts()

Country
United States     13
India              2
Italy              1
Morocco            1
Netherlands        1
United Kingdom     1
Japan              1
Lithuania          1
Australia          1
Pakistan           1
Name: count, dtype: int64

### **7. Find the list of Indian states where the people have purchased the things under the category Technology.**

In [41]:
indian_states = (df["Category"] == "Technology") & (df["Country"] == "India")

In [42]:
indian_states_details = df[indian_states]

In [43]:
indian_states_details[:3]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
41,29272,IN-2015-BF1100558-42319,2015-11-11,2015-11-15,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,TEC-PH-5269,Technology,Phones,"Motorola Smart Phone, with Caller ID",4518.78,7,0.0,632.52,658.69,High
48,28701,IN-2015-SW2027558-42125,2015-05-01,2015-05-01,Same Day,SW-2027558,Scott Williamson,Consumer,NaN,Jamshedpur,...,TEC-MA-5007,Technology,Machines,"Konica Inkjet, White",2174.13,7,0.0,500.01,637.86,Critical
55,29047,IN-2013-SG2047058-41424,2013-05-30,2013-05-31,First Class,SG-2047058,Sheri Gordon,Consumer,NaN,Bhopal,...,TEC-CO-4590,Technology,Copiers,"Hewlett Wireless Fax, Color",1526.52,4,0.0,732.72,625.77,Critical

In [44]:
indian_states_details["State"].value_counts()

State
Maharashtra          62
Uttar Pradesh        47
Tamil Nadu           33
Rajasthan            24
Madhya Pradesh       23
Karnataka            21
Gujarat              20
Delhi                17
Andhra Pradesh       15
Haryana              13
Telangana            13
Bihar                11
West Bengal          11
Chhattisgarh         10
Punjab               10
Kerala                6
Jharkhand             4
Odisha                4
Jammu and Kashmir     4
Uttarakhand           3
Puducherry            2
Assam                 1
Name: count, dtype: int64

### **8. Find the overall rank of "India" where the 'Profit' is maximum under the category 'Technology'.**

In [45]:
df["Profit"]  = df["Profit"].astype(str).str.strip()

In [46]:
if df["Profit"].astype(str).str.contains("$",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace("$","",regex = False).copy()
    
if df["Profit"].astype(str).str.contains(",",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace(",","",regex = False).copy()

if df["Profit"].astype(str).str.contains("(",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace("(","",regex = False).copy()

if df["Profit"].astype(str).str.contains(")",regex = False).any():
    df["Profit"] = df["Profit"].astype(str).str.replace(")","",regex = False).copy()

In [47]:
df["Profit"] = pd.to_numeric(df["Profit"], errors="coerce")

In [53]:
tech = df[df["Category"] == "Technology"]

country_profit = tech.groupby("Country")["Profit"].sum().reset_index()

country_profit["Rank"] = country_profit["Profit"].rank(method="dense", ascending=False)

india_rank = country_profit[country_profit["Country"] == "India"]["Rank"].values[0]

print(india_rank)

5.0

### **9. Display the data with min, max, average and std of 'Profit' & 'Sales' for each Sub-Category under each Category**